---
apiVersion: v1
kind: Secret
metadata:
  name: ausfcfg
  namespace: openfaas-fn
type: Opaque
stringData: 
  ausfcfg.yml: | 
    info:
      version: 1.0.3
      description: AUSF initial local configuration

    configuration:
      serviceNameList:
        - nausf-auth

      sbi:
        scheme: http
        registerIPv4: gateway-proxy.gloo-system.svc.cluster.local
        ##registerIPv4: free5gc-core-free5gc-ausf-service # IP used to register to NRF
        bindingIPv4: 0.0.0.0  # IP used to bind the service
        ##port change beacuse of binding permissions. permissions needed for port 80
        port: 80
        tls:
          key: ../cert/ausf.key
          pem: ../cert/ausf.pem
      # modify the URL to point to a service that is in a different namespace
      nrfUri: http://nrf-nnrf.free5gc.svc.cluster.local:8000
      plmnSupportList:
        - mcc: 208
          mnc: 93
        - mcc: 123
          mnc: 45
      groupId: ausfGroup001
      eapAkaSupiImsiPrefix: false

    logger:
      enable: true
      level: debug 
      reportCaller: true
