<<<<<<< HEAD
= Usuful guide for using minikube and kubectl
Paula López Medina 
v1.0, 2020-12
// Metadata
:keywords: kubeshark 
// Create TOC wherever needed
:toc: macro
:sectanchors:
:sectnumlevels: 2
:sectnums: 
:source-highlighter: pygments
:imagesdir: images
// Start: Enable admonition icons
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
// Icons for GitHub
:yes: :heavy_check_mark:
:no: :x:
endif::[]
ifndef::env-github[]
:icons: font
// Icons not for GitHub
:yes: icon:check[]
:no: icon:times[]
endif::[]
// End: Enable admonition icons

This documentation contains the information necesary to install and use minikube for creating and managing local clusters aswell as the information for using kubectl for interacting with the minikube cluster

// Create the Table of contents here
toc::[]

== Introduction

In this documentation we will see how to install minikube which is a simple Kubernetes distribution that allows you to create and interacte with a local cluster. The tool for interacting with minikube is kubectl which we weill also install and leran the useful commands for interacting.

== Instalation
For installing minikube and start it:

[source,bash]
----
wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
sudo cp minikube-linux-amd64 /usr/local/bin/minikube
sudo chmod +x /usr/local/bin/minikube
----

For installing kubectl for interacting with the minikube cluster:

[source,bash]
----
curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
chmod +x kubectl
sudo mv kubectl /usr/local/bin/
----


== Usuful commands

First we will need to create the cluster
[source,bash]
----
minikube start

----

In case we want to check if it was created you can check with docker 

[source,bash]
----
docker ps

----

For interacting with the cluster we will use kubectl. First for creating a namespace

[source,bash]
----
kubectl create ns <name-namespace>
----

For cheacking all the namespaces

[source,bash]
----
kubectl get ns
----

to get all the pods running
[source,bash]
----
kubectl get pods -A
----

For getting info about IP and port where minikube is running
[source,bash]
----
kubectl cluster-info
----
=======
= Usuful guide for using minikube and kubectl
Paula López Medina 
v1.0, 2020-12
// Metadata
:keywords: kubeshark 
// Create TOC wherever needed
:toc: macro
:sectanchors:
:sectnumlevels: 2
:sectnums: 
:source-highlighter: pygments
:imagesdir: images
// Start: Enable admonition icons
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
// Icons for GitHub
:yes: :heavy_check_mark:
:no: :x:
endif::[]
ifndef::env-github[]
:icons: font
// Icons not for GitHub
:yes: icon:check[]
:no: icon:times[]
endif::[]
// End: Enable admonition icons

This documentation contains the information necesary to install and use minikube for creating and managing local clusters aswell as the information for using kubectl for interacting with the minikube cluster

// Create the Table of contents here
toc::[]

== Introduction

In this documentation we will see how to install minikube which is a simple Kubernetes distribution that allows you to create and interacte with a local cluster. The tool for interacting with minikube is kubectl which we weill also install and leran the useful commands for interacting.

== Instalation
For installing minikube and start it:

[source,bash]
----
wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
sudo cp minikube-linux-amd64 /usr/local/bin/minikube
sudo chmod +x /usr/local/bin/minikube
----

For installing kubectl for interacting with the minikube cluster:

[source,bash]
----
curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
chmod +x kubectl
sudo mv kubectl /usr/local/bin/
----


== Usuful commands

First we will need to create the cluster
[source,bash]
----
minikube start

----

In case we want to check if it was created you can check with docker 

[source,bash]
----
docker ps

----

For interacting with the cluster we will use kubectl. First for creating a namespace

[source,bash]
----
kubectl create ns <name-namespace>
----

For cheacking all the namespaces

[source,bash]
----
kubectl get ns
----

to get all the pods running
[source,bash]
----
kubectl get pods -A
----

For getting info about IP and port where minikube is running
[source,bash]
----
kubectl cluster-info
----
>>>>>>> 6f0808e6fafd551a83fa05de2f68db8b3f801b3b
